export const MovieGenre = {
  ADVENTURE: 12,
  FANTASY: 14,
  ANIMATION: 16,
  DRAMA: 18,
  HORROR: 27,
  ACTION: 28,
  COMEDY: 35,
  HISTORY: 36,
  WESTERN: 37,
  THRILLER: 53,
  CRIME: 80,
  DOCUMENTARY: 99,
  SCIENCE_FICTION: 878,
  MYSTERY: 9648,
  MUSIC: 10402,
  ROMANCE: 10749,
  WAR: 10752,
  FAMILY: 10751,
  TV_MOVIE: 10770,
} as const;

export const genreDataMap = {
  [MovieGenre.ADVENTURE]: { label: "Adventure" },
  [MovieGenre.FANTASY]: { label: "Fantasy" },
  [MovieGenre.ANIMATION]: { label: "Animation" },
  [MovieGenre.DRAMA]: { label: "Drama" },
  [MovieGenre.HORROR]: { label: "Horror" },
  [MovieGenre.ACTION]: { label: "Action" },
  [MovieGenre.COMEDY]: { label: "Comedy" },
  [MovieGenre.HISTORY]: { label: "History" },
  [MovieGenre.WESTERN]: { label: "Western" },
  [MovieGenre.THRILLER]: { label: "Thriller" },
  [MovieGenre.CRIME]: { label: "Crime" },
  [MovieGenre.DOCUMENTARY]: { label: "Documentary" },
  [MovieGenre.SCIENCE_FICTION]: { label: "Science Fiction" },
  [MovieGenre.MYSTERY]: { label: "Mystery" },
  [MovieGenre.MUSIC]: { label: "Music" },
  [MovieGenre.ROMANCE]: { label: "Romance" },
  [MovieGenre.WAR]: { label: "War" },
  [MovieGenre.FAMILY]: { label: "Family" },
  [MovieGenre.TV_MOVIE]: { label: "TV Movie" },
} as const;
